export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const SET_NATIONALITY = "SET_NATIONALITY";
export const DELETE_USER = "DELETE_USER";
export const SEARCH_USER = "SEARCH_USER";
export const USER_DETAILS = "USER_DETAILS";
