export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCH_MORE_USERS = "FETCH_MORE_USERS";
export const FETCH_MORE_USERS_REQUEST = "FETCH_MORE_USERS_REQUEST";
export const FETCH_MORE_USERS_SUCCESS = "FETCH_MORE_USERS_SUCCESS";
export const FETCH_MORE_USERS_FAILURE = "FETCH_MORE_USERS_FAILURE";
export const FETCH_WITH_NATIONALITY_REQUEST = "FETCH_WITH_NATIONALITY_REQUEST";
export const FETCH_WITH_NATIONALITY_SUCCESS = "FETCH_WITH_NATIONALITY_SUCCESS";
export const FETCH_WITH_NATIONALITY_FAILURE = "FETCH_WITH_NATIONALITY_FAILURE";
export const FETCH_MORE_WITH_NATIONALITY_REQUEST =
  "FETCH_MORE_WITH_NATIONALITY_REQUEST";
export const FETCH_MORE_WITH_NATIONALITY_SUCCESS =
  "FETCH_MORE_WITH_NATIONALITY_SUCCESS";
export const FETCH_MORE_WITH_NATIONALITY_FAILURE =
  "FETCH_MORE_WITH_NATIONALITY_FAILURE";
export const GET_NATIONALITY = "GET_NATIONALITY";
export const DELETE_USER = "DELETE_USER";
export const SEARCH_USER = "SEARCH_USER";
